/* ============================================================
   PostgreSQL DDL (converted from your MySQL DDL)
   - AUTO_INCREMENT  -> GENERATED BY DEFAULT AS IDENTITY
   - DATETIME        -> TIMESTAMP (without time zone)
   - JSON            -> JSONB
   - MySQL inline ENUM -> PostgreSQL ENUM TYPEs (created once)
   ============================================================ */

-- 1) ENUM TYPES (idempotent creation)
DO $$ BEGIN
CREATE
TYPE status_enum AS ENUM ('DELETE', 'ACTIVE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE member_grade_enum AS ENUM ('NORMAL', 'VIP', 'VVIP');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE payment_method_enum AS ENUM ('CARD', 'BANK_TRANSFER', 'AUTO_DEBIT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE product_type_enum AS ENUM ('MOBILE_PLAN', 'ADDON', 'TV');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE billing_type_enum AS ENUM ('RECURRING', 'PER_USE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE subscription_status_enum AS ENUM ('ACTIVE', 'SUSPENDED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE unit_type_enum AS ENUM ('GB', 'MIN', 'COUNT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE discount_type_enum AS ENUM ('SELECTIVE_CONTRACT', 'ETC');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE discount_method_enum AS ENUM ('RATE', 'AMOUNT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE contract_status_enum AS ENUM ('ACTIVE', 'EXPIRED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE usage_type_enum AS ENUM ('DATA', 'VOICE', 'SMS', 'ADDON_USAGE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE charge_type_enum AS ENUM ('MICRO_PAYMENT', 'CONTENT_FEE', 'APP_PURCHASE', 'ROAMING', 'ETC');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE bill_send_status_enum AS ENUM ('BEFORE_SENT', 'SENT', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE bill_item_category_enum AS ENUM ('SUBSCRIPTION', 'OVER_USAGE', 'ONE_TIME_PURCHASE', 'DISCOUNT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE bill_item_subcategory_enum AS ENUM (
        'PLAN','ADDON','TV',
        'DATA_OVER','VOICE_OVER','SMS_OVER','ADDON_OVER',
        'MICRO_PAYMENT','CONTENT_FEE',
        'SELECTIVE_CONTRACT','FAMILY_BUNDLE','PROMOTION','ETC'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE bill_channel_enum AS ENUM ('EMAIL', 'SMS');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE bill_notification_status_enum AS ENUM ('READY', 'SENT', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE
TYPE reservation_status_enum AS ENUM ('SCHEDULED', 'DONE', 'FAILED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- 2) TABLES
CREATE TABLE IF NOT EXISTS member
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                      VARCHAR(50)  NOT NULL,
    phone_number              VARCHAR(255) NOT NULL,
    email                     VARCHAR(255) NOT NULL,
    address                   VARCHAR(255) NOT NULL,
    member_grade member_grade_enum NOT NULL,

    payment_owner_name        VARCHAR(100) NOT NULL,
    payment_name              VARCHAR(100) NOT NULL,
    payment_number            VARCHAR(100) NOT NULL,
    payment_method payment_method_enum NOT NULL,

    notification_day_of_month SMALLINT     NULL,
    do_not_disturb_start_time TIME         NULL,
    do_not_disturb_end_time   TIME         NULL,

    created_date              TIMESTAMP    NOT NULL,
    modified_date             TIMESTAMP    NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_member PRIMARY KEY (id)
);

-- COMMENT ON COLUMN member.notification_day_of_month IS '1~31';


CREATE TABLE IF NOT EXISTS product
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)   NOT NULL,
    price_amount  DECIMAL(18, 0) NOT NULL,
    billing_type billing_type_enum NOT NULL,
    product_type product_type_enum NOT NULL,

    created_date  TIMESTAMP      NOT NULL,
    modified_date TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_product PRIMARY KEY (id)
);

-- COMMENT ON COLUMN product.price_amount IS '월 가격(원), 무료 상품이면 0을 명시적으로 저장';


CREATE TABLE IF NOT EXISTS mobile_plan_spec
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id    BIGINT         NOT NULL,
    data_gb       DECIMAL(10, 3) NULL,
    voice_minutes INTEGER        NULL,
    sms_count     INTEGER        NULL,

    created_date  TIMESTAMP      NOT NULL,
    modified_date TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_mobile_plan_spec PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS addon_spec
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id        BIGINT         NOT NULL,
    unit_type unit_type_enum NOT NULL,
    unit_price_amount DECIMAL(18, 0) NOT NULL,

    created_date      TIMESTAMP      NOT NULL,
    modified_date     TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_addon_spec PRIMARY KEY (id)
);

-- COMMENT ON COLUMN addon_spec.unit_price_amount IS '단위당 과금액(원)';


CREATE TABLE IF NOT EXISTS tv_spec
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id    BIGINT    NOT NULL,
    channel_count INTEGER   NOT NULL,

    created_date  TIMESTAMP NOT NULL,
    modified_date TIMESTAMP NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_tv_spec PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS subscription
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id     BIGINT    NOT NULL,
    product_id    BIGINT    NOT NULL,
    subscription_status subscription_status_enum NOT NULL,

    created_date  TIMESTAMP NOT NULL,
    modified_date TIMESTAMP NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_subscription PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS device
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)   NOT NULL,
    price         DECIMAL(18, 0) NOT NULL,

    created_date  TIMESTAMP      NOT NULL,
    modified_date TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_device PRIMARY KEY (id)
);

-- COMMENT ON COLUMN device.price IS '출고가(원)';


CREATE TABLE IF NOT EXISTS member_device
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id          BIGINT         NOT NULL,
    device_id          BIGINT         NOT NULL,
    purchase_price     DECIMAL(18, 0) NOT NULL,
    installment_months SMALLINT       NOT NULL DEFAULT 1,
    purchased_at       TIMESTAMP      NOT NULL,

    created_date       TIMESTAMP      NOT NULL,
    modified_date      TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_member_device PRIMARY KEY (id)
);

-- COMMENT ON COLUMN member_device.purchase_price IS '실 구매가(원)';
-- COMMENT ON COLUMN member_device.installment_months IS '일시불=1';
-- COMMENT ON COLUMN member_device.purchased_at IS '구매 발생 시각';


CREATE TABLE IF NOT EXISTS discount_policy
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    discount_name  VARCHAR(255)   NOT NULL,
    discount_type discount_type_enum NOT NULL,
    discount_method discount_method_enum NOT NULL,
    discount_value DECIMAL(18, 6) NOT NULL,

    created_date   TIMESTAMP      NOT NULL,
    modified_date  TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_discount_policy PRIMARY KEY (id)
);

-- COMMENT ON COLUMN discount_policy.discount_type IS '선택약정 포함(SELECTIVE_CONTRACT)';


CREATE TABLE IF NOT EXISTS subscription_discount
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    discount_policy_id  BIGINT    NOT NULL,
    subscription_id     BIGINT    NOT NULL,
    contract_start_date DATE      NULL,
    contract_end_date   DATE      NULL,
    contract_status contract_status_enum NOT NULL,

    created_date        TIMESTAMP NOT NULL,
    modified_date       TIMESTAMP NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_subscription_discount PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS subscription_usage
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subscription_id BIGINT         NOT NULL,
    usage_yyyymm    VARCHAR(6)        NOT NULL,
    usage_type usage_type_enum NOT NULL,
    quantity        DECIMAL(18, 3) NOT NULL DEFAULT 0,
    unit_type unit_type_enum NOT NULL,

    created_date    TIMESTAMP      NOT NULL,
    modified_date   TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_subscription_usage PRIMARY KEY (id)
);

-- COMMENT ON COLUMN subscription_usage.usage_yyyymm IS '예: 202601';


CREATE TABLE IF NOT EXISTS one_time_purchase
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id     BIGINT         NOT NULL,
    name          VARCHAR(255)   NOT NULL,
    amount        DECIMAL(18, 0) NOT NULL,
    charge_type charge_type_enum NOT NULL,
    charged_at    TIMESTAMP      NOT NULL,

    created_date  TIMESTAMP      NOT NULL,
    modified_date TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_one_time_purchase PRIMARY KEY (id)
);

-- COMMENT ON COLUMN one_time_purchase.amount IS '과금액(원)';
-- COMMENT ON COLUMN one_time_purchase.charged_at IS '과금 발생 시각';


CREATE TABLE IF NOT EXISTS bill
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id                   BIGINT         NOT NULL,
    billing_yyyymm              VARCHAR(6)        NOT NULL,

    total_amount                DECIMAL(18, 0) NOT NULL DEFAULT 0,
    vat                         DECIMAL(18, 0) NOT NULL DEFAULT 0,
    unpaid_amount               DECIMAL(18, 0) NOT NULL DEFAULT 0,
    total_discount_amount       DECIMAL(18, 0) NOT NULL DEFAULT 0,
    total_billed_amount         DECIMAL(18, 0) NOT NULL DEFAULT 0,

    due_date                    DATE           NULL,
    approval_expected_date      DATE           NULL,

    bill_send_status bill_send_status_enum NULL,

    payment_owner_name_snapshot VARCHAR(100)   NOT NULL,
    payment_name_snapshot       VARCHAR(100)   NOT NULL,
    payment_number_snapshot     VARCHAR(100)   NOT NULL,

    created_date                TIMESTAMP      NOT NULL,
    modified_date               TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_bill PRIMARY KEY (id)
);

-- COMMENT ON COLUMN bill.billing_yyyymm IS '예: 202601';


CREATE TABLE IF NOT EXISTS bill_item
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bill_id       BIGINT         NOT NULL,

    item_category bill_item_category_enum NOT NULL,
    item_subcategory bill_item_subcategory_enum NULL,
    item_name     VARCHAR(255)   NOT NULL,

    amount        DECIMAL(18, 0) NOT NULL DEFAULT 0,
    detail_snapshot JSONB NULL,

    created_date  TIMESTAMP      NOT NULL,
    modified_date TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_bill_item PRIMARY KEY (id)
);

-- COMMENT ON COLUMN bill_item.amount IS '항상 양수. DISCOUNT는 차감으로 해석';


CREATE TABLE IF NOT EXISTS bill_notification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bill_id       BIGINT    NOT NULL,
    channel bill_channel_enum NOT NULL,
    send_status bill_notification_status_enum NOT NULL,

    created_date  TIMESTAMP NOT NULL,
    modified_date TIMESTAMP NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_bill_notification PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS receipt
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bill_id       BIGINT         NOT NULL,
    paid_at       TIMESTAMP      NOT NULL,
    payment_method payment_method_enum NOT NULL,
    paid_amount   DECIMAL(18, 0) NOT NULL DEFAULT 0,

    created_date  TIMESTAMP      NOT NULL,
    modified_date TIMESTAMP      NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_receipt PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS reservation_notification
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    target_billing_yyyymm VARCHAR(6)   NOT NULL,
    scheduled_send_at     TIMESTAMP NOT NULL,
    reservation_status reservation_status_enum NOT NULL,

    created_date          TIMESTAMP NOT NULL,
    modified_date         TIMESTAMP NOT NULL,
    status status_enum NOT NULL,

    CONSTRAINT pk_reservation_notification PRIMARY KEY (id)
);

-- COMMENT ON COLUMN reservation_notification.target_billing_yyyymm IS '대상 청구 연월(예: 202601)';
-- COMMENT ON COLUMN reservation_notification.scheduled_send_at IS '예약 발송 일시';


-- 3) FOREIGN KEYS (same formatting style as you used)
ALTER TABLE subscription
    ADD CONSTRAINT fk_subscription_to_member
        FOREIGN KEY (member_id)
            REFERENCES member (id);

ALTER TABLE subscription
    ADD CONSTRAINT fk_subscription_to_product
        FOREIGN KEY (product_id)
            REFERENCES product (id);

ALTER TABLE mobile_plan_spec
    ADD CONSTRAINT fk_mobile_plan_spec_to_product
        FOREIGN KEY (product_id)
            REFERENCES product (id);

ALTER TABLE tv_spec
    ADD CONSTRAINT fk_tv_spec_to_product
        FOREIGN KEY (product_id)
            REFERENCES product (id);

ALTER TABLE addon_spec
    ADD CONSTRAINT fk_addon_spec_to_product
        FOREIGN KEY (product_id)
            REFERENCES product (id);

ALTER TABLE subscription_discount
    ADD CONSTRAINT fk_subscription_discount_to_discount_policy
        FOREIGN KEY (discount_policy_id)
            REFERENCES discount_policy (id);

ALTER TABLE subscription_discount
    ADD CONSTRAINT fk_subscription_discount_to_subscription
        FOREIGN KEY (subscription_id)
            REFERENCES subscription (id);

ALTER TABLE subscription_usage
    ADD CONSTRAINT fk_subscription_usage_to_subscription
        FOREIGN KEY (subscription_id)
            REFERENCES subscription (id);

ALTER TABLE one_time_purchase
    ADD CONSTRAINT fk_one_time_purchase_to_member
        FOREIGN KEY (member_id)
            REFERENCES member (id);

ALTER TABLE bill
    ADD CONSTRAINT fk_bill_to_member
        FOREIGN KEY (member_id)
            REFERENCES member (id);

ALTER TABLE bill_item
    ADD CONSTRAINT fk_bill_item_to_bill
        FOREIGN KEY (bill_id)
            REFERENCES bill (id);

ALTER TABLE bill_notification
    ADD CONSTRAINT fk_bill_notification_to_bill
        FOREIGN KEY (bill_id)
            REFERENCES bill (id);

ALTER TABLE receipt
    ADD CONSTRAINT fk_receipt_to_bill
        FOREIGN KEY (bill_id)
            REFERENCES bill (id);

ALTER TABLE member_device
    ADD CONSTRAINT fk_member_device_to_member
        FOREIGN KEY (member_id)
            REFERENCES member (id);

ALTER TABLE member_device
    ADD CONSTRAINT fk_member_device_to_device
        FOREIGN KEY (device_id)
            REFERENCES device (id);